# -*- coding: utf-8 -*-
"""session_1_tasks (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wvsBiNgHQjhBi4RRyDxKRsh_AvK6XrOg

# Task : Session 1
Solve these questions own your own and try to test yourself what you have learned in the session.

Happy Learning!

### Q1 :- Print the given strings as per stated format.

**Given strings**:
```
"Data" "Science" "Mentorship" "Program"
"By" "CampusX"
```
**Output**:
```
Data-Science-Mentorship-Program-started-By-CampusX
```

Concept- [Seperator and End]
"""

print("Data" ,"Science" ,"Mentorship" ,"Program","By" ,"CampusX",sep="-")

"""### Q2:- Write a program that will convert celsius value to fahrenheit."""

cel=int(input("write temperature in celcius"))
fahren=(cel*9/5)+32
print("temperature in fahrenheit is " , fahren)

"""### Q3:- Take 2 numbers as input from the user.Write a program to swap the numbers without using any special python syntax."""

one=int(input("write first number"))
two=int(input("write second number"))
print("first number before swapping " ,one)
print("second number before swapping " ,two)
temp=one
one=two
two=temp
print("first number after swapping " ,one)
print("second number after swapping " ,two)

"""### Q4:- Write a program to find the euclidean distance between two coordinates.Take both the coordinates from the user as input."""

x1=int(input("write first x coordinate "))
x2=int(input("write second x coordinate "))
y1=int(input("write first y coordinate "))
y2=int(input("write second y coordinate "))
eucli=((((x2-x1)**2)+((y2-y1)**2))**(1/2))
print("euclidean distance is ", eucli)

"""### Q5:- Write a program to find the simple interest when the value of principle,rate of interest and time period is provided by the user.

"""

prin=int(input("write principal amount"))
rate=int(input("write rate"))
time=int(input("write time "))
si=(prin*rate*time)/100
print("simple interest is " , si)

"""### Q6:- Write a program that will tell the number of dogs and chicken are there when the user will provide the value of total heads and legs.

For example:
Input:
heads -> 4
legs -> 12
<br>
Output:
dogs -> 2
chicken -> 2




"""



"""### Q7:- Write a program to find the sum of squares of first n natural numbers where n will be provided by the user."""

n=int(input("how many numbers?"))
i=1
sum=0
for i in range(n+1):
  sq=i**2
  sum=sum+sq
print("sum is ",sum)

"""### Q8:- Given the first 2 terms of an Arithmetic Series.Find the Nth term of the series. Assume all inputs are provided by the user."""

n1=int(input("enter the first number of series "))
n2=int(input("enter the second number of series"))
num=int(input("which number of series do you want?"))
d=n2-n1
series=n1+(num-1)*d
print(series)

"""### Q9:- Given 2 fractions, find the sum of those 2 fractions.Take the numerator and denominator values of the fractions from the user."""

num1=int(input("first numerator"))
num2=int(input("second numerator"))
den1=int(input("first denominator"))
den2=int(input("second denominator"))
deno=den1*den2
nume=num1*den2+num2*den1
print(nume , "/" , deno)

"""### Q10:- Given the height, width and breadth of a milk tank, you have to find out how many glasses of milk can be obtained? Assume all the inputs are provided by the user.



Input:<br>
Dimensions of the milk tank<br>
H = 20cm, L = 20cm, B = 20cm
<br><br>
Dimensions of the glass<br>
h = 3cm, r = 1cm
"""

height=int(input("height"))
width=int(input("width"))
breadth=int(input("breadth"))
heightglass=int(input("height of glass"))
radius=int(input("radius of glass"))
volume_of_tank=height*width*breadth
volume_of_glass=3.14*(radius**2)*heightglass
fill=volume_of_tank//volume_of_glass
print(fill)

